# Generated by Django 3.2.8 on 2021-10-18 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_auto_20211018_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('city', models.CharField(max_length=150, verbose_name='Город')),
                ('full_adress', models.CharField(max_length=150, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Адресс электронной потчы')),
                ('orderings', models.PositiveIntegerField(default=0, verbose_name='Количество заказов')),
            ],
            options={
                'verbose_name_plural': 'Клиенты',
                'db_table': 'clients',
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_list', models.TextField(verbose_name='Полный текст заказа')),
                ('final_price', models.PositiveIntegerField(verbose_name='Финальная цена заказа')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
                ('delivery', models.BooleanField(verbose_name='Доставка (да или нет)')),
                ('time', models.DateTimeField(verbose_name='Время заказа')),
                ('adress', models.CharField(blank=True, max_length=150, null=True, verbose_name='Адрес доставки')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients_system.client', verbose_name='Клиент')),
                ('products', models.ManyToManyField(to='products.Product', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'orders',
            },
        ),
    ]
